-- AlterEnum
ALTER TYPE "CourseAccessLevel" ADD VALUE 'CLONE_AND_VIEW';

-- AlterTable
ALTER TABLE "GroupScore" ALTER COLUMN "finalScore" SET DEFAULT 0,
ALTER COLUMN "finalScore" SET DATA TYPE DOUBLE PRECISION;

-- AlterTable
ALTER TABLE "Score" ALTER COLUMN "finalScore" SET DEFAULT 0,
ALTER COLUMN "finalScore" SET DATA TYPE DOUBLE PRECISION;
